name: github_activity
description: Github activity tracker for mobile.
environment:
  sdk: '^3.1.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.1.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
