name: github_activity
flutter:
  uses-material-design: true
description: Github activity tracker for mobile.
environment:
  sdk: '^3.1.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.1.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  shared_preferences:
  material_design_icons_flutter: 7.0.7296
dev_dependencies:
  hive_generator:
  build_runner: ^2.4.7
